name: ArcaneSurvival
version: 0.1.0-SNAPSHOT
main: arcaneSurvival.ArcaneSurvival
description: Arcane Survival Essentials
authors: [Agentred100, Jugglingman456, SimonOrJ]
commands:
  arcane:
    description: Arcane help
  arcanesurvival:
    description: Arcane identify
  arc:
    description: Arcane shortcut
  ytorgonak:
   description: Ytorgonak!
  ytor:
   description: Ytorgonak alias!
  sharpshootingace:
   description: SharpshootingAce!
  sharp:
   description: SharpshootingAce alias!
  tell:
   usage: /msg <player> <message>
   description: msg command redirect
