name: ArcaneServer
version: ${project.version}
authors: [Agentred100, jugglingman456, Morios, SimonOrJ]
description: Arcane Survival Network Essentials
main: com.arcaneminecraft.server.ArcaneServer
website: https://arcaneminecraft.com/

depend: [ArcaneAPI]
softdepend: [LuckPerms]

commands:
  afk:
    description: Mark yourself as afk
    usage: /afk
  global:
    aliases: [g]
    usage: /global <chat message ...>
  help:
    aliases: ["?"]
    usage: /help [page|command name]
  kill:
    description: End the suffering of your life just to revive you on a click of a button
    usage: /kill
  local:
    aliases: [l]
    usage: /local <local message ...>
  localrange:
    aliases: [localradius, lr]
    usage: /localrange [radius]
  localtoggle:
    aliases: [lt]
    usage: /localtoggle
  opme:
    usage: /opme
    permission: arcane.command.opme
  setworldspawn:
    permission: minecraft.command.setworldspawn
  spawn:
    usage: /spawn
  username:
    description: Display your username!
    usage: /username
  uuid:
    description: Get player's UUID
    usage: /uuid <player>

permissions:
  # @Deprecated
  # Arcane role permissions
  arcane.admin:
    children:
      arcane.role.admin: true
      arcane.build: true
  arcane.mod:
    children:
      arcane.role.mod: true
      arcane.build: true
  arcane.chatmod:
    children:
      arcane.role.chatmod: true
      arcane.build: true
  arcane.donor:
    children:
      arcane.role.donor: true
      arcane.build: true
    default: false
  arcane.trusted:
    children:
      arcane.build: true
    default: op

  # Show role
  arcane.role.admin:
    description: Adds "Admin | " to playerlist.
    children:
      arcane.role.mod: true
      arcane.role.chatmod: true
  arcane.role.mod:
    description: Adds "Mod | " to playerlist.
    children:
      arcane.role.chatmod: true
  arcane.role.chatmod:
    description: Adds "Chatmod | " to playerlist.
  arcane.role.donor:
    description: Adds "Donor | " to playerlist.
    default: false

  # Allow features for players
  arcane.build:
    description: Allow building and giving/taking items on the server
    default: true
  arcane.homes:
    description: Arcane extra home donor.
    default: false
  arcane.tabcomplete.hidecolon:
    description: Hides commands with colon (e.g. bukkit:version).
    default: not op

  # Command-based permissions
  arcane.command.help.details:
    description: Shows origin of each entry in /help
    default: op
  arcane.command.local:
    description: Allows /local, /localchat, and /localradius
    default: true
  arcane.command.spawn:
    description: Allows /spawn
    default: true
  arcane.command.opme:
    description: Allows /opme
    default: false
  arcane.command.uuid:
    description: Allows /uuid
    default: true

  # Arcane anticheat/moderation hook
  arcane.spy.on.xray:
    description: Logs x-ray alert when mining an ore
    default: not op
  arcane.spy.on.sign:
    description: Logs sign creation/modification message
    default: not op
  arcane.spy.on.command: # ArcaneBungee node
    description: Logs command messages. Critical commands are not ignored.

  # ArcaneBungee uses these nodes; the registeration is for sake of easy autocomplete.
  arcane.spy.receive.xray:
    description: Receive x-ray alerts
  arcane.spy.receive.sign:
    description: Receive sign creation/modification content
  arcane.spy.receive.command:
    description: Receive critical command messages
  arcane.spy.receive.command.all:
    description: Receive all command messages
