name: ArcaneServer
version: ${project.version}
authors: [Agentred100, jugglingman456, Morios, SimonOrJ]
description: Arcane Survival Network Essentials
main: com.arcaneminecraft.server.ArcaneServer
website: https://arcaneminecraft.com/

depend: [ArcaneAPI]
softdepend: [LuckPerms]

commands:
  afk:
    usage: /afk
  help:
    aliases: ["?"]
  opme:
    usage: /opme
  kill:
    description: Lets players self-destruct
    usage: /kill
  username:
    description: Display your username!
    usage: /username

permissions:
  arcane.admin:
    description: Arcane Administrator.
    children:
      arcane.mod: true
      arcane.chatmod: true
  arcane.mod:
    description: Arcane Moderator.
    children:
      arcane.chatmod: true
  arcane.chatmod:
    description: Arcane Chatmod.
  arcane.trusted:
    description: Arcane greylisted players.
    default: op
  arcane.donor:
    description: Arcane donor.
    default: false
  arcane.homes:
    description: Arcane extra home donor.
    default: op
  arcane.tabcomplete.hidecolon:
    description: Hides commands with colon (e.g. bukkit:version).
    default: not op
  arcane.command.opme:
    description: Allows /opme
    default: false
  arcane.command.help.showorigin:
    description: Shows origin of each entry in /help
    default: op