name: ArcaneServer
version: ${project.version}
authors: [Agentred100, jugglingman456, Morios, SimonOrJ]
description: Arcane Survival Network Essentials
main: com.arcaneminecraft.server.ArcaneServer
website: https://arcaneminecraft.com/

depend: [ArcaneAPI]
softdepend: [LuckPerms]

commands:
  afk:
    description: Mark yourself as afk
    usage: /afk
  global:
    aliases: [g]
    usage: /g <chat message ...>
  help:
    aliases: ["?"]
    usage: /help [page|command name]
  local:
    aliases: [l]
    usage: /local <local message ...>
  localradius:
    aliases: [lr]
    usage: /localradius [radius]
  localtoggle:
    aliases: [lt]
    usage: /localtoggle [on|off]
  opme:
    usage: /opme
    permission: arcane.command.opme
  kill:
    description: End the suffering of your life just to revive you on a click of a button
    usage: /kill
  username:
    description: Display your username!
    usage: /username
  uuid:
    description: Get player's UUID
    usage: /uuid <player>

permissions:
  # @Deprecated
  # Arcane role permissions
  arcane.admin:
    description: Arcane Administrator.
    children:
      arcane.mod: true
      arcane.chatmod: true
  arcane.mod:
    description: Arcane Moderator.
    children:
      arcane.chatmod: true
  arcane.chatmod:
    description: Arcane Chatmod.
  arcane.trusted:
    description: Arcane greylisted players.
    default: op
  arcane.donor:
    description: Arcane donor.
    default: false
  arcane.homes:
    description: Arcane extra home donor.
    default: op

  arcane.tabcomplete.hidecolon:
    description: Hides commands with colon (e.g. bukkit:version).
    default: not op
  arcane.command.help.details:
    description: Shows origin of each entry in /help
    default: op
  arcane.command.local:
    description: Allows /local, /localchat, and /localradius
    default: true
  arcane.command.opme:
    description: Allows /opme
    default: false
  arcane.command.uuid:
    description: Allows /uuid
    default: true

  # Arcane anticheat/moderation hook
  arcane.spy.on.xray:
    description: Logs x-ray alert when mining an ore
    default: not op
  arcane.spy.on.sign:
    description: Logs sign creation/modification message
    default: not op
  arcane.spy.on.command: # ArcaneBungee node
    description: Logs command messages. Critical commands are not ignored.
    default: not op

  # ArcaneBungee uses these nodes; the registeration is for sake of easy autocomplete.
  arcane.spy.receive.xray:
    description: Receive x-ray alerts
    default: op
  arcane.spy.receive.sign:
    description: Receive sign creation/modification content
    default: op
  arcane.spy.receive.command:
    description: Receive critical command messages
    default: op
  arcane.spy.receive.command.all:
    description: Receive all command messages
    default: op
