name: ArcaneServer
version: @version@
authors: [Agentred100, jugglingman456, Morios, SimonOrJ]
description: Arcane Survival Network Essentials
main: com.arcaneminecraft.server.ArcaneServer
website: https://arcaneminecraft.com/
api-version: 1.13

depend: [ArcaneAPI]
softdepend: [LuckPerms]

commands:
  afk:
    description: Mark yourself as afk
    usage: /afk
  diamondstoneratio:
    aliases: [diastone, ds]
    description: Checks the player's x-ray potential (Diamonds:Stone)
    usage: /diamondtostoneratio <player>
    #TODO: or /xraycheck <blockFrom blockTo> [player]
    permission: arcane.command.diamondstoneeratio
  gms:
    aliases: [gm0]
    usage: /gms
    permission: arcane.command.gms
  gmc:
    aliases: [gm1]
    usage: /gmc
    permission: arcane.command.gmc
  gma:
    aliases: [gm2]
    usage: /gma
    permission: arcane.command.gma
  gmsp:
    aliases: [gm3]
    usage: /gmsp
    permission: arcane.command.gmsp
  global:
    aliases: [g]
    usage: /global <chat message ...>
  help:
    aliases: ["?"]
    usage: /help [page|command name]
  kill:
    description: End the suffering of your life just to revive you with a click of a button
    usage: /kill
    permission: arcane.command.kill
  killdeathratio:
    aliases: [killdeath, kd]
    description: Get the K/D ratio for player
    usage: /killdeathratio [player]
    permission: arcane.command.killdeathratio
  local:
    aliases: [l]
    usage: /local <local message ...>
    permission: arcane.command.local
  localrange:
    aliases: [localradius, lr]
    usage: /localrange [radius]
    permission: arcane.command.local
  localtoggle:
    aliases: [lt]
    usage: /localtoggle
    permission: arcane.command.local
  opme:
    usage: /opme
    permission: arcane.command.opme
  setworldspawn:
    permission: minecraft.command.setworldspawn
  spawn:
    aliases: [s, splawn]
    usage: /spawn
    permission: arcane.command.spawn
  username:
    description: Display your username!
    usage: /username
  uuid:
    description: Get player's UUID
    usage: /uuid <player>
    permission: arcane.command.uuid

permissions:
  # Allow features for players
  arcane.build:
    description: Allow building and giving/taking items on the server
    default: true
  arcane.homes:
    description: Arcane extra home donor.
    default: false
  arcane.afk.stayonfullserver:
    description: Doesn't kick this player when the server is full and the player is afk
    default: false
  arcane.afk.getkickmessage:
    description: Gets message and clickable coordinates about a player's imminent death while they were afk
    default: op

  # Command-based permissions
  arcane.command.afk.other:
    description: Allows player to set others to afk
    default: op
  arcane.command.diamondstoneratio:
    description: Allows /diamondstoneratio
    default: op

  arcane.command.gm*:
    description: Allows /gm<s|c|a|sp>
    default: op
    children:
      arcane.command.gms: true
      arcane.command.gmc: true
      arcane.command.gma: true
      arcane.command.gmsp: true
  arcane.command.gm*.other:
    description: Allows /gm<s|c|a|sp> <player>
    default: op
    children:
      arcane.command.gms.other: true
      arcane.command.gmc.other: true
      arcane.command.gma.other: true
      arcane.command.gmsp.other: true
  arcane.command.gms:
    description: Allows /gms
    default: op
  arcane.command.gms.other:
    description: Allows /gms <player>
    default: op
    children:
      arcane.command.gms: true
  arcane.command.gmc:
    description: Allows /gmc
    default: op
  arcane.command.gmc.other:
    description: Allows /gmc <player>
    default: op
    children:
      arcane.command.gmc: true
  arcane.command.gma:
    description: Allows /gma
    default: op
  arcane.command.gma.other:
    description: Allows /gma <player>
    default: op
    children:
      arcane.command.gma: true
  arcane.command.gmsp:
    description: Allows /gmsp
    default: op
  arcane.command.gmsp.other:
    description: Allows /gmsp <player>
    default: op
    children:
      arcane.command.gmsp: true

  arcane.command.help.details:
    description: Shows origin of each entry in /help
    default: op
  arcane.command.kill:
    description: Allows /kill only to kill themselves
    default: op
  arcane.command.killdeathratio:
    description: Allows /killdeathratio
    default: true
  arcane.command.local:
    description: Allows /local, /localchat, and /localradius
    default: true
  arcane.command.spawn:
    description: Allows /spawn
    default: true
  arcane.command.opme:
    description: Allows /opme
    default: false
  arcane.command.uuid:
    description: Allows /uuid
    default: true

  # Arcane anticheat/moderation hook
  arcane.spy.on.xray:
    description: Logs x-ray alert when mining an ore
    default: false
  arcane.spy.on.sign:
    description: Logs sign creation/modification message
    default: false
  arcane.spy.on.command: # ArcaneBungee node
    description: Logs commands
    default: false
  arcane.spy.on.command.all: # ArcaneBungee node
    description: Logs commands regardless of if it's ignored
    default: false


  # ArcaneBungee uses these nodes; the registeration is for sake of easy autocomplete.
  arcane.spy.receive.xray:
    description: Receive x-ray alerts
    default: false
  arcane.spy.receive.sign:
    description: Receive sign creation/modification content
    default: false
  arcane.spy.receive.command:
    description: Receive only critical command messages
    default: false
  arcane.spy.receive.command.all:
    description: Receive all command messages
    default: false
